services:
  docs:
    image: {{ project_slug }}_local_docs
    container_name: {{ project_slug }}_local_docs
    build:
      context: .
      dockerfile: ./docker/local/docs/Dockerfile
    env_file:
      - ./.env
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./{{ project_slug }}:/app/{{ project_slug }}:z
    ports:
      - '9000:9000'
    command: /start-docs
